spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:ec2-18-203-205-71.eu-west-1.compute.amazonaws.com}:${POSTGRES_PORT:5432}/${POSTGRES_DB:d7m986j6673psa}
    username: ${POSTGRES_USER:sthpocajxjturj}
    password: ${POSTGRES_PASSWORD:d4e8ca764a5eb837e777c6315dac656dbb16d34c8c079e57e4533d9f28013c3b}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true
    properties.hibernate.enable_lazy_load_no_trans: true

jwt:
  secret: ${JWT_SECRET:635266556A586E3272357538782F413F4428472B4B6250645367566B50}
