spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: false
    properties.hibernate.enable_lazy_load_no_trans: true

